language: generic
services:
  - docker

env:
  global:
    - CODE_COVERAGE="true"
  matrix:
    - ROS_DISTRO="melodic"
install:
  - git clone --quiet --depth 1 https://github.com/rarrais/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
