language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="melodic"  CATKIN_LINT=true  BUILDER=catkin_make DOCKER_RUN_OPTS='-e CATKIN_TEST_COVERAGE=1'

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh