language: generic
services:
  - docker

env:
  global:
    - AFTER_SCRIPT='bash <(curl -s https://raw.githubusercontent.com/rarrais/ros_coverage/master/code-coverage.sh)'
    - CI_ENV=`bash <(curl -s https://raw.githubusercontent.com/rarrais/ros_coverage/master/ci_env.sh)`
    - DOCKER_RUN_OPTS='$CI_ENV -e CODACY_REPORT="true" -e CODECOV_REPORT="true" -e ADDITIONAL_DEBS="python-coverage curl jq gcovr"'
  matrix:
    - ROS_DISTRO="melodic"
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh