language: generic
services:
  - docker

env:
  global:
    - CODE_COVERAGE=`bash <(curl -s https://raw.githubusercontent.com/rarrais/ros_coverage/develop/ros_coverage.sh)`
    - DOCKER_RUN_OPTS=$CODE_COVERAGE
  matrix:
    - ROS_DISTRO="melodic"  CODACY="true"  CODECOV="true"
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh