language: generic
services:
  - docker

env:
  global:
    - BEFORE_INIT='bash <(curl -s https://raw.githubusercontent.com/rarrais/ros_coverage/master/travis.sh)'
  matrix:
    - ROS_DISTRO="melodic"
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
