language: generic
services:
  - docker

env:
  global:
    - AFTER_SCRIPT='./after_script.sh'
  matrix:
    - ROS_DISTRO="melodic"  CATKIN_LINT=true  BUILDER=catkin_make ADDITIONAL_DEBS="python-coverage curl" DOCKER_RUN_OPTS='-e CATKIN_TEST_COVERAGE=1 -e CMAKE_CXX_FLAGS=--coverage -e CODACY_PROJECT_TOKEN'
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
